WalletKitCore/WalletKitCoreTests/test/hedera/testHedera.c
WalletKitCore/src/generic/BRGenericHedera.c
WalletKitCore/src/generic/BRGenericManager.c
WalletKitCore/src/generic/BRGenericRipple.c
WalletKitCore/src/hedera/BRHederaSerialize.c
WalletKitCore/src/hedera/BRHederaTransaction.c
WalletKitCore/src/hedera/BRHederaTransaction.h
WalletKitSwift/WalletKitDemo/Source/TransferCreateSendController.swift

Added the memo support via the TransferAttributes

CORE-881: In Hedera, add memo support

---

WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/ExperimentalApi.java
WalletKitSwift/WalletKit/common/BRBlockChainDB.swift

Avoid repeatedly 'GET account_transactions/' is it is an indirect indicator of Hedera Account existence.

CORE-892: On Hedera Account Creation repeatedly 'GET accounts/'

---

WalletKitCore/Package.swift
WalletKitCore/src/bitcoin/BRWalletManager.c
WalletKitCore/src/hedera/BRHederaTransaction.c
WalletKitCore/src/ripple/BRRippleTransaction.c
WalletKitSwift/Package.swift

[Ignore Package.swift cleanups]  A couple of scary ones here...

CORE-894: Fix Static Analysis Issues

---

WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Transaction.java
WalletKitSwift/WalletKit/BRCryptoSystem.swift
WalletKitSwift/WalletKit/common/BRBlockChainDB.swift

Merge `Transfer` into `Transaction` metadata.

CORE-918: Add 'metaData' to BlockChainDB.Model.Transaction

---

WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
WalletKitCore/src/ethereum/ewm/BREthereumEWM.c

We no longer have an 'account balances' endpoint.  Update the wallet balance as each transfer is handled.

CORE-919: Update the ETH/TOK Wallet Balances

---

WalletKitCore/src/crypto/BRCryptoTransfer.c
WalletKitCore/src/crypto/BRCryptoTransferP.h
WalletKitCore/src/crypto/handlers/btc/BRCryptoTransferBTC.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c

`sourceAddress`, `targetAddress, `feeBasisEstimated`

CORE-924: Add additional parameters to cryptoTransferAllocAndInit

---

WalletKitCore/src/crypto/BRCryptoClient.c
WalletKitCore/src/crypto/BRCryptoNetwork.c
WalletKitCore/src/crypto/BRCryptoTransfer.c
WalletKitCore/src/crypto/BRCryptoTransferP.h
WalletKitCore/src/crypto/BRCryptoWalletManager.c
WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
WalletKitCore/src/crypto/BRCryptoWalletManagerP.h
WalletKitCore/src/crypto/handlers/btc/BRCryptoTransferBTC.c
WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletManagerBTC.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoETH.h
WalletKitCore/src/crypto/handlers/eth/BRCryptoTransferETH.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletETH.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
WalletKitSwift/WalletKit/BRCryptoSystem.swift
WalletKitSwift/WalletKit/common/BRBlockChainDB.swift

Also pulled in some changes from staging/core-7.0.0, cherry picked.

CORE-925: Handlers for 'EstimateFeeBasis'

---

WalletKitCore/src/crypto/BRCryptoHash.c
WalletKitCore/src/ethereum/base/BREthereumAddress.h
WalletKitCore/src/ethereum/base/BREthereumBase.h
WalletKitCore/src/ethereum/base/BREthereumEther.c
WalletKitCore/src/ethereum/base/BREthereumHash.h
WalletKitCore/src/ethereum/bcs/BREthereumBCS.c
WalletKitCore/src/ethereum/bcs/BREthereumBCSSync.c
WalletKitCore/src/ethereum/blockchain/BREthereumBlock.c
WalletKitCore/src/ethereum/blockchain/BREthereumTransaction.c
WalletKitCore/src/ethereum/contract/BREthereumToken.c
WalletKitCore/src/ethereum/event/BREventAlarm.c
WalletKitCore/src/ethereum/ewm/BREthereumEWM.c
WalletKitCore/src/ethereum/ewm/BREthereumEWMClient.c
WalletKitCore/src/ethereum/ewm/BREthereumEWMPrivate.h
WalletKitCore/src/ethereum/les/BREthereumLES.c
WalletKitCore/src/ethereum/les/BREthereumNode.c
WalletKitCore/src/ethereum/les/BREthereumProvision.c
WalletKitCore/src/ethereum/les/msg/BREthereumMessagePIP.c
WalletKitCore/src/ethereum/util/BRUtilMathParse.c
WalletKitCore/src/generic/BRGenericBase.h
WalletKitCore/src/ripple/BRRippleAddress.c
WalletKitCore/src/ripple/BRRippleSerialize.c
WalletKitCore/src/ripple/BRRippleTransaction.c
WalletKitCore/src/ripple/BRRippleUtils.c

Should be no functional changes; except two ETH issues found and fixed.

CORE-944: Compiler Warnings

---

WalletKitSwift/WalletKit/BRCryptoSystem.swift

Key change was to add `(flags: .barrier)` to `{add, rem}WalletFeeEstimateHandler()`.  Other changes for clarity.

CORE-953: Ensure SystemCallbackCoordinator modifications are thread-safe

---

WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/System.java
WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java
WalletKitJava/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/CoreSystemListener.java
WalletKitJava/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/WalletListActivity.java
WalletKitSwift/WalletKit/BRCryptoSystem.swift
WalletKitSwift/WalletKit/common/BRBlockChainDB.swift
WalletKitSwift/WalletKitDemo/Source/CoreDemoAppDelegate.swift

Draft: Pending Java updates; pending `System.configure()` retry on immediate 'pause'

CORE-954: Cleanups for repeated disconnect/connect 

---

WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
WalletKitCore/src/crypto/BRCryptoWallet.c
WalletKitCore/src/crypto/BRCryptoWalletManager.c
WalletKitCore/src/generic/BRGeneric.c
WalletKitCore/src/generic/BRGeneric.h
WalletKitCore/src/generic/BRGenericHandlers.h
WalletKitCore/src/generic/BRGenericHedera.c
WalletKitCore/src/generic/BRGenericRipple.c
WalletKitCore/src/ripple/BRRippleBase.h
WalletKitCore/src/ripple/BRRippleWallet.c
WalletKitCore/src/ripple/BRRippleWallet.h

The balance will go negative... but then eventually, when all transfers 'arrive', will be non-negative.

CORE-977: In Core Generic, Handle a Negative Wallet Balance

---

WalletKitSwift/WalletKit/BRCryptoSystem.swift

This is a work-around pending CORE-959

CORE-990: Workaround `System.configure()`

---

WalletKitCore/include/BRCryptoClient.h
WalletKitCore/src/crypto/BRCryptoClient.c
WalletKitCore/src/support/BRSet.c
WalletKitCore/src/support/BRSet.h
WalletKitSwift/WalletKit/BRCryptoSystem.swift

Note: Fix BTC/BCH/BSV HD Wallet address handling.
Transactions found via 'refactor2020' now agree with this found via 'master-brd-app'.

CORE-1011: Define cryptoClientQRYRequestTransactionsOrTransfers()

---

WalletKitCore/include/BRCryptoListener.h
WalletKitCore/src/crypto/BRCryptoConfig.h
WalletKitCore/src/crypto/BRCryptoTransfer.c
WalletKitCore/src/crypto/BRCryptoTransferP.h
WalletKitCore/src/crypto/BRCryptoWallet.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerP2PETH.c
WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
WalletKitSwift/WalletKitDemo/Source/WalletViewController.swift

Various fixes... 
But the JIRA issue is not fully *tested*; blocked by CORE-1018.  The fee is observed to change in the ERC20 transfer; but not observed yet for a) the ETH fee transfer nor b) the ETH balance.  Will be covered in CORE-1018.

CORE-1007: Handle a Fee Change when Included

---

WalletKitSwift/WalletKit/BRCryptoClient.swift
WalletKitSwift/WalletKit/BRCryptoSystem.swift
WalletKitSwift/WalletKit/common/BRCryptoBlockset.swift

As an errorMessage; extract from the Blockset error data JSON.

CORE-1008: In SystemClientError, add an Optional(String) to .response.

---

WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
WalletKitSwift/WalletKitDemo/Source/TransferTableViewCell.swift
WalletKitSwift/WalletKitDemo/Source/TransferViewController.swift

Also fixed the XRP unit tests (missed commit for CORE-1019 merge).

CORE-1020: In XRP and HBAR, handle 'included w/ error' transfers.

---

WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
WalletKitCore/src/crypto/handlers/xtz/BRCryptoAddressXTZ.c
WalletKitCore/src/crypto/handlers/xtz/BRCryptoTransferXTZ.c
WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletManagerXTZ.c
WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletXTZ.c
WalletKitCore/src/tezos/BRTezosAddress.c
WalletKitCore/src/tezos/BRTezosAddress.h
WalletKitCore/src/tezos/BRTezosFeeBasis.c
WalletKitSwift/WalletKit/BRCryptoSystem.swift

- handle single cumulative fee transfer
- add logic to include burn transfers (target "unknown") when recovering from transaction bundle
- apply changes from CORE-1020
(recreated #124 with new base)

CORE-1023: Update Tezos transfer bundle processing

---

WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c

[Still not fully correct, regarding 'loan' balance.]
Address crash, for now.

CORE-1030: Attempt to handle a BREthereumExchange w/ or w/o a NULL contract

---

WalletKitCore/src/tezos/BRTezosTransaction.c
WalletKitSwift/WalletKitDemo/Source/Base.lproj/Main.storyboard
WalletKitSwift/WalletKitDemo/Source/TransferCreateDelegateController.swift
WalletKitSwift/WalletKitDemo/Source/WalletViewController.swift
WalletKitSwift/WalletKitDemo/WalletKitDemo.xcodeproj/project.pbxproj

CORE-1042: Add delegation feature to demo app
CORE-1044: Support cancelling delegation by passing wallet address as target to create transfer

CORE-1042 / CORE-1044: Tezos delegation

---

WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java

Make the Java code consistent with the Swift code.  A non-zero amount would be handled by another transfer.

CORE-1046: In System.mergeTransfers() set the `transferWithFee` amount to '0'

---

WalletKitCore/include/BRCryptoNetwork.h
WalletKitCore/include/BRCryptoWalletManagerClient.h
WalletKitCore/src/crypto/BRCryptoHash.c
WalletKitCore/src/crypto/BRCryptoNetwork.c
WalletKitCore/src/crypto/BRCryptoNetworkP.h
WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
WalletKitCore/src/generic/BRGeneric.c
WalletKitCore/src/generic/BRGeneric.h
WalletKitCore/src/generic/BRGenericBase.h
WalletKitCore/src/generic/BRGenericHandlers.h
WalletKitCore/src/generic/BRGenericHedera.c
WalletKitCore/src/generic/BRGenericManager.c
WalletKitCore/src/generic/BRGenericRipple.c
WalletKitCore/src/generic/BRGenericTezos.c
WalletKitCore/src/tezos/BRTezosBase.h
WalletKitSwift/WalletKit/BRCryptoSystem.swift
WalletKitSwift/WalletKit/common/BRBlockChainDB.swift

Capture verified block hash from BlockchainDB

CORE-1047: Add support for Tezos Base58 hash encoding/decoding

---

WalletKitCore/src/generic/BRGenericTezos.c
WalletKitSwift/WalletKitDemo/Source/Base.lproj/Main.storyboard
WalletKitSwift/WalletKitDemo/Source/TransferCreateDelegateController.swift
WalletKitSwift/WalletKitDemo/Source/WalletViewController.swift
WalletKitSwift/WalletKitDemo/WalletKitDemo.xcodeproj/project.pbxproj

Cherry picked CORE-1042 from staging/core-9.0.0 branch.

CORE-1045: Add delegate attribute to Tezos transfers

---

WalletKitCore/src/crypto/BRCryptoClient.c
WalletKitCore/src/crypto/BRCryptoFileService.c
WalletKitCore/src/crypto/BRCryptoNetwork.c
WalletKitCore/src/crypto/BRCryptoWalletManager.c
WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletManagerBTC.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletManagerXTZ.c

Excludes two memory issue; both related to syncing which has not threading issues.  Will address these two later.

CORE-1057: Manage BRCryptoHash memory

---

WalletKitCore/src/crypto/handlers/btc/BRCryptoAddressBTC.c
WalletKitCore/src/crypto/handlers/btc/BRCryptoBTC.h
WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletSweeperBTC.c
WalletKitSwift/WalletKit/BRCryptoWalletManager.swift
WalletKitSwift/WalletKitDemo/Source/WalletViewController.swift

add function to create BCH address from legacy BTC address string

CORE-981: add support for BCH wallet sweep

---

WalletKitJava/corecrypto-android/build.gradle
WalletKitJava/corecrypto-jre/build.gradle
WalletKitJava/corenative-android/build.gradle
WalletKitJava/corenative-jre/build.gradle
WalletKitJava/crypto/build.gradle
WalletKitJava/gradle/publish.gradle

- Apply platform specific publishing plugin dynamically
- Create and include sources jars for maven publishing

Publish JVM source artifacts to maven

---

WalletKitCore/WalletKitCoreTests/test/tezos/testTezos.c
WalletKitCore/src/generic/BRGenericTezos.c
WalletKitCore/src/tezos/BRTezosFeeBasis.c
WalletKitCore/src/tezos/BRTezosFeeBasis.h
WalletKitCore/src/tezos/BRTezosTransaction.c
WalletKitCore/src/tezos/BRTezosWallet.c
WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java

… to handle unit costs lower than 1 mutez / byte

CORE-1069: Track transaction size in kb for Tezos fee basis 

---

WalletKitCore/src/generic/BRGenericTezos.c
WalletKitCore/src/tezos/BRTezosEncoder.c
WalletKitCore/src/tezos/BRTezosFeeBasis.c
WalletKitCore/src/tezos/BRTezosFeeBasis.h
WalletKitCore/src/tezos/BRTezosTransaction.c
WalletKitCore/src/tezos/BRTezosTransfer.c

Apply minimal cost per byte in fee calculation.

CORE-1076: Rework BRTezosFeeBasis mapping to BRGenericFeeBasis.

---

WalletKitCore/WalletKitCoreTests/test/hedera/testHedera.c
WalletKitCore/src/crypto/BRCryptoWalletManager.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletHBAR.c
WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
WalletKitCore/src/hedera/BRHederaTransaction.c
WalletKitCore/src/hedera/BRHederaTransaction.h

Create a serialization for each known Hedera node

CORE-910: Hedera multiple serializations

---

WalletKitCore/src/crypto/BRCryptoWalletManager.c
WalletKitCore/src/generic/BRGeneric.c
WalletKitCore/src/generic/BRGeneric.h
WalletKitCore/src/generic/BRGenericHandlers.h
WalletKitCore/src/generic/BRGenericHedera.c
WalletKitCore/src/generic/BRGenericRipple.c
WalletKitCore/src/generic/BRGenericTezos.c
WalletKitCore/src/tezos/BRTezosTransaction.c
WalletKitCore/src/tezos/BRTezosTransaction.h
WalletKitCore/src/tezos/BRTezosTransfer.c
WalletKitCore/src/tezos/BRTezosTransfer.h

Adds a 'gen function'; set as NULL for XRP, HBAR.

CORE-1100: Update BRTezos{Transfer,Transaction} fee, when included/errored.

---

WalletKitCore/src/crypto/handlers/eth/BRCryptoTransferETH.c
WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerP2PETH.c
WalletKitSwift/WalletKit/BRCryptoTransfer.swift

Crashes discovered during 'Ropsten on Blockset' submit testing.

CORE-1124: Fix Crash on ETH Submit

---

WalletKitCore/WalletKitCoreExplore/createtransactions.c
WalletKitCore/WalletKitCoreExplore/createtransactions.h
WalletKitCore/WalletKitCoreExplore/main.c

When needing to test submits, fee estimates, etc

Add transaction creation code to "Explore"

---

WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletETH.c
WalletKitSwift/WalletKitDemo/Source/TransferCreateSendController.swift

Should allow an ETH 'max send' to succeed.  Previously the 'max' didn't include margin; thus for the submit `max + fee(w/ margin) > balance`.  Now there is no margin applied to a Ether transfer w/ an estimate of 21,000.  For other Ether estimates, indicating a default smart contract function, the max will still be off. (A rare occurrance; covered by another post-core-9.0 fix).

CORE-1225: Don't apply gasLimit margin to a gas estimate of 21000

---

WalletKitCore/src/walletkit/handlers/xtz/WKWalletManagerXTZ.c
WalletKitCore/src/walletkit/handlers/xtz/WKWalletXTZ.c

Bring over the `master` changes.

CORE-1222: In XTZ, match transfers `ByHashOrUids()`

---

CONTRIBUTORS
WalletKitCore/CMakeLists.txt
WalletKitCore/WalletKitCoreTests/WalletKitCoreTests.swift
WalletKitCore/WalletKitCoreTests/test/avax/testAvalanche.c
WalletKitCore/WalletKitCoreTests/test/include/test.h
WalletKitCore/include/WKBase.h
WalletKitCore/src/avalanche/BRAvalanche.h
WalletKitCore/src/avalanche/BRAvalancheAccount.c
WalletKitCore/src/avalanche/BRAvalancheAccount.h
WalletKitCore/src/avalanche/BRAvalancheAddress.c
WalletKitCore/src/avalanche/BRAvalancheAddress.h
WalletKitCore/src/avalanche/BRAvalancheBase.h
WalletKitCore/src/avalanche/BRAvalancheFeeBasis.c
WalletKitCore/src/avalanche/BRAvalancheFeeBasis.h
WalletKitCore/src/avalanche/BRAvalancheTransaction.c
WalletKitCore/src/avalanche/BRAvalancheTransaction.h
WalletKitCore/src/walletkit/WKConfig.h
WalletKitCore/src/walletkit/handlers/avax/WKAVAX.h
WalletKitCore/src/walletkit/handlers/avax/WKAccountAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKAddressAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKFeeBasisAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKHandlersAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKNetworkAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKTransferAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKWalletAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKWalletManagerAVAX.c
WalletKitJava/WalletKit/src/main/java/com/blockset/walletkit/NetworkType.java
WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/Utilities.java
WalletKitJava/WalletKitNative/src/main/java/com/blockset/walletkit/nativex/WKNetworkType.java
WalletKitSwift/WalletKit/WKNetwork.swift

CORE-1199: generate avax templates

---

WalletKitCore/WalletKitCoreTests/test/avax/testAvalanche.c
WalletKitCore/src/avalanche/BRAvalancheAccount.c
WalletKitCore/src/avalanche/BRAvalancheAccount.h
WalletKitCore/src/avalanche/BRAvalancheAddress.c
WalletKitCore/src/avalanche/BRAvalancheAddress.h
WalletKitCore/src/avalanche/BRAvalancheBase.h
WalletKitCore/src/avalanche/BRAvalancheTransaction.c
WalletKitCore/src/walletkit/handlers/avax/WKAddressAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKTransferAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKWalletAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKWalletManagerAVAX.c

Modifies the template file for Avalanche; pulls in 'prototype' functions.

CORE-1194: Implement BRAvalanceAddress

---

WalletKitCore/WalletKitCoreTests/test/avax/testAvalanche.c
WalletKitCore/src/avalanche/BRAvalancheAccount.h
WalletKitCore/src/avalanche/BRAvalancheBase.h
WalletKitCore/src/avalanche/BRAvalancheNetwork.c
WalletKitCore/src/avalanche/BRAvalancheTransaction.c
WalletKitCore/src/avalanche/BRAvalancheTransaction.h
WalletKitCore/src/support/BRData.h
WalletKitCore/src/support/BROSCompat.c
WalletKitCore/src/support/BROSCompat.h
WalletKitCore/src/walletkit/handlers/avax/WKAVAX.h
WalletKitCore/src/walletkit/handlers/avax/WKWalletAVAX.c
WalletKitCore/src/walletkit/handlers/avax/WKWalletManagerAVAX.c

Marked as a 'draft' as there is more to come; but this is expected to be the bulk of the work.  All 'prototype' tests pass; the fuji transaction of https://testnet.avascan.info/blockchain/x/tx/2T7WkhEYnypDQFGfB8LgNKkfPhVsmBsdyfPfy7fTm6XnaV2DXS has been reproduced.

CORE-1196: BRAvalancheTransaction

---

WalletKitCore/WalletKitCoreExplore/createtransactions.c
WalletKitCore/WalletKitCoreExplore/main.c
WalletKitCore/src/tezos/BRTezosOperation.c

@carlcherry , the 'Explore' `createtransaction.{ch}` for XTZ is disabled.

CORE-1289: Fix `WalletKitCoreExplore`

---

WalletKitCore/WalletKitCoreTests/test/stellar/testStellar.c
WalletKitCore/src/stellar/BRStellarAddress.c

CORE-1292: Validate Stellar address strings

---

WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/Wallet.java
WalletKitSwift/WalletKit/WKWallet.swift

Confirmed with the Java/Swift Core Demo Apps

CORE-1296: Return the 'balance' on a Tezos Fee Estimation failure.

---

README.md

DRAFT, pending additional review comments.

CORE-1290: Address PR comments for walletkit-0.10.0 merge to master

---

WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/Wallet.java
WalletKitSwift/WalletKit/WKWallet.swift

On accounts w/ `balance < fee`, could see a negative amount.

CORE-1307: On `estimateLimitMaximum` ensure 'transferAmount > 0`.

---

WalletKitCore/WalletKitCoreTests/WalletKitCoreTests.swift
WalletKitCore/include/WKAccount.h
WalletKitCore/src/walletkit/WKAccount.c
WalletKitCore/src/walletkit/WKAccountP.h
WalletKitCore/src/walletkit/handlers/btc/WKAccountBTC.c
WalletKitCore/src/walletkit/handlers/eth/WKAccountETH.c
WalletKitCore/src/walletkit/handlers/hbar/WKAccountHBAR.c
WalletKitCore/src/walletkit/handlers/xlm/WKAccountXLM.c
WalletKitCore/src/walletkit/handlers/xrp/WKAccountXRP.c
WalletKitCore/src/walletkit/handlers/xtz/WKAccountXTZ.c
WalletKitJava/WalletKit/src/main/java/com/blockset/walletkit/Account.java
WalletKitJava/WalletKit/src/main/java/com/blockset/walletkit/Api.java
WalletKitJava/WalletKitBRD/src/commonTest/java/com/blockset/walletkit/brd/AccountAIT.java
WalletKitJava/WalletKitBRD/src/commonTest/java/com/blockset/walletkit/brd/HelpersAIT.java
WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/Account.java
WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/ApiProvider.java
WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/DemoApplication.java
WalletKitJava/WalletKitNative/src/main/java/com/blockset/walletkit/nativex/WKAccount.java
WalletKitJava/WalletKitNative/src/main/java/com/blockset/walletkit/nativex/library/WKNativeLibraryDirect.java
WalletKitSwift/WalletKit/WKAccount.swift
WalletKitSwift/WalletKitDemo/Source/CoreDemoAppDelegate.swift
WalletKitSwift/WalletKitTests/Tests/WKAccountTests.swift
WalletKitSwift/WalletKitTests/Tests/WKBaseTests.swift

BIP 44 paths are accounted for during account creation when the network type is testnet

CORE-1320: BTC Testnet Transaction Signing Fails
