- WalletKitCore/include/BRCryptoAccount.h
- WalletKitJava/CoreNative/src/commonTest/java/com/breadwallet/corenative/CryptoLibraryIT.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoAccount.java
- WalletKitJava/corecrypto/src/commonTest/java/com/breadwallet/corecrypto/AccountAIT.java
- WalletKitJava/corecrypto/src/commonTest/java/com/breadwallet/corecrypto/HelpersAIT.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/Account.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/CryptoApiProvider.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/Account.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/CryptoApi.java
- WalletKitJava/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java
- WalletKitSwift/WalletKit/BRCryptoAccount.swift
Functionally, there is no change.  Make Swift/Java consistent; but both assume a paperKey produces an Account, always.
> CORE-876: Account.create() as consistently `Optional`

- WalletKitCore/include/BRCryptoBase.h
- WalletKitCore/src/crypto/BRCryptoConfig.h
- WalletKitCore/src/crypto/BRCryptoNetwork.c
- WalletKitSwift/WalletKit/BRCryptoNetwork.swift
- WalletKitSwift/WalletKitDemo/Source/CoreDemoAppDelegate.swift
This puts the top-level linkages in place for Stellar.  Allows for generic/BRGenericStellar.{ch} implementation of the GEN interface (see CORE-775)
> CORE-878: Define CRYPTO_NETWORK_TYPE_XLM

- WalletKitCore/src/generic/BRGeneric.c
- WalletKitCore/src/generic/BRGenericBase.h
- WalletKitCore/src/generic/BRGenericHedera.c
- WalletKitCore/src/generic/BRGenericManager.c
- WalletKitCore/src/generic/BRGenericRipple.c
Support XRP @ 32 bytes; HBAR @ 48 bytes.  Limit is 64 bytes.
> CORE-879: Make BRGenericHash w/a Variable Size

- WalletKitCore/src/generic/BRGenericHedera.c
This appears to occur because transfers may arrive in random order (when loaded from the BRFileSystem) and sometimes the 'sent' transfers overwhelm the 'recv' transfers, momentarily.
> CORE-896: Dont allow a Hedera wallet to have a negative balance.

- WalletKitCore/src/bitcoin/BRWalletManager.c
This commit was missed in the breadwallet-core -> walletkit repo conversion.
> CORE-874: In `bwmHandleTxAdded()`, don't dereference `refedTransaction`

- WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
- WalletKitCore/src/ripple/BRRippleTransaction.c
- WalletKitCore/src/ripple/BRRippleTransaction.h
1. There were a couple of missing break statements when parsing
field codes/types which could cause a crash or currupt data
2. Add the feeBasis values when creating a tx from raw bytes
3. Update unit tests to check source, target, feeBasis, fee,
destinationTag, amount, txType, sequence.
> CORE-909: In Core Ripple, fix raw tx parsing

- WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
- WalletKitCore/src/ripple/BRRippleAccount.c
- WalletKitCore/src/ripple/BRRippleAccount.h
- WalletKitCore/src/ripple/BRRippleTransfer.c
- WalletKitCore/src/ripple/BRRippleTransfer.h
- WalletKitCore/src/ripple/BRRippleWallet.c
Ripple account created after block 55313921 use a different sequence number start point.
> CORE-915: Ripple - Support new sequence number start

- WalletKitCore/src/bitcoin/BRSyncManager.c
- WalletKitCore/src/generic/BRGenericManager.c
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
If Blockset does not provide a blockHeight, then the transaction/transfer is not in the blockchain.  Don't resolve the blockheight optional with ZERO but will BLOCK_HEIGHT_UNBOUND.  Then in BTC/BCH code use TX_UNCONFIRMED.  For GEN handle the state carefully.
> CORE-911: In Core Crypto, Handled Blockset `SUBMITTED` but not `INCLUDED`

- WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
- WalletKitCore/src/generic/BRGenericManager.c
- WalletKitCore/src/ripple/BRRippleAccount.c
- WalletKitCore/src/ripple/BRRippleWallet.c
Our wallet can end up with transfers that pre-date our account:
i.e. someone sends us less than 20 XRP and transaction fails
When determining the block number where our account is created
ignore failed transfers directed at us.
Add unit test to cover the above case.
> CORE-928: Fix Ripple sequence error

- WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
(No Java change; did not have 'address.lowecased()' work-around)
> CORE-929: For 'ETH in Blockset', Query w/ Multiple Address String Cases.

- WalletKitCore/src/crypto/BRCryptoNetwork.c
This will be unnecessary; but it is not harmful.
> CORE-932: Make `cryptoNetworkGetCurrencyForUids()` case-insensitive.

- WalletKitCore/CMakeLists.txt
- WalletKitCore/WalletKitCoreTests/test/ethereum/testEwm.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
- WalletKitCore/src/ethereum/bcs/BREthereumBCS.h
- WalletKitCore/src/ethereum/blockchain/BREthereumLog.c
- WalletKitCore/src/ethereum/blockchain/BREthereumTransactionStatus.c
- WalletKitCore/src/ethereum/blockchain/BREthereumTransactionStatus.h
- WalletKitCore/src/ethereum/contract/BREthereumExchange.c
- WalletKitCore/src/ethereum/contract/BREthereumExchange.h
- WalletKitCore/src/ethereum/ewm/BREthereumClient.h
- WalletKitCore/src/ethereum/ewm/BREthereumEWM.c
- WalletKitCore/src/ethereum/ewm/BREthereumEWM.h
- WalletKitCore/src/ethereum/ewm/BREthereumEWMClient.c
- WalletKitCore/src/ethereum/ewm/BREthereumEWMEvent.c
- WalletKitCore/src/ethereum/ewm/BREthereumEWMPrivate.h
- WalletKitCore/src/ethereum/ewm/BREthereumTransfer.c
- WalletKitCore/src/ethereum/ewm/BREthereumTransfer.h
- WalletKitCore/src/ethereum/ewm/BREthereumWallet.c
- WalletKitCore/src/ethereum/ewm/BREthereumWallet.h
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
This started as 'get the account nonce correct'... and morphed into 'handle internal transactions'
This involved adding `BREthereumExchange`, an analog to `BREtheremLog`, which represents an arbitrary exchange of an asset that in not a) ETH in a transaction nor b) a known ERC20 token transfer via a LogEvent.
The asset for a `BREthereumExchange' can be either ETH or TOK.  The exchange becomes the basis for a BRCryptoTransfer and thus a wallet could hold transfers with a basis of: Transaction and/or Exchange or Log and/or Exchange.
Rewrite BREthereumTransaction to handle an exchange?  Can't because a transaction has a nonce and an exchange cannot result in a nonce increment.
Rewrite BREtheremLog to handle an exchange?  BREthereumLog is a concept handled in the P2P Light Client - with a …
> CORE-940: Add BREthereumExchange

- WalletKitCore/CMakeLists.txt
- WalletKitCore/WalletKitCoreTests/WalletKitCoreTests.swift
- WalletKitCore/WalletKitCoreTests/test/bitcoin/test.c
- WalletKitCore/WalletKitCoreTests/test/bitcoin/testBwm.c
- WalletKitCore/WalletKitCoreTests/test/crypto/testCrypto.c
- WalletKitCore/WalletKitCoreTests/test/include/test.h
- WalletKitCore/include/BRCryptoBase.h
- WalletKitCore/src/bitcoin/BRSyncManager.c
- WalletKitCore/src/bitcoin/BRWalletManager.c
- WalletKitCore/src/bitcoin/BRWalletManager.h
- WalletKitCore/src/bsv/BRBSVParams.c
- WalletKitCore/src/bsv/BRBSVParams.h
- WalletKitCore/src/crypto/BRCryptoAddress.c
- WalletKitCore/src/crypto/BRCryptoConfig.h
- WalletKitCore/src/crypto/BRCryptoNetwork.c
- WalletKitCore/src/crypto/BRCryptoNetworkP.h
- WalletKitCore/src/crypto/BRCryptoPayment.c
- WalletKitCore/src/crypto/BRCryptoWallet.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
- WalletKitCore/src/ethereum/Makefile
- WalletKitSwift/WalletKit/BRCryptoNetwork.swift
- WalletKitSwift/WalletKitDemo/Source/Base.lproj/Main.storyboard
- WalletKitSwift/WalletKitDemo/Source/CoreDemoAppDelegate.swift
- WalletKitSwift/WalletKitDemo/Source/TransferViewController.swift
Added network definition and chain params for BSV mainnet and testnet. Update logic for BTC/BCH address handling to support BSV (legacy) addresses.
> CORE-933: Add support for Bitcoin SV

- WalletKitJava/CoreNative/CMakeLists.txt
- WalletKitJava/CoreNative/build.gradle
- WalletKitJava/CoreNative/src/main/cpp/core
- WalletKitSwift/WalletKitTests/Tests/BRCryptoBaseTests.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoSystemTests.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoTransferTests.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoWalletManagerTests.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoWalletTests.swift
All Swift UnitTests pass except for: `testTransferBTC_P2P()` and `testSubscription()` - neither is ETH related.
All Java UnitTest pass except: `testNetworkETH` on a hardcoded fee basis comparison (that can't succeed with dynamic fee from Blockset) and `testAmountCreateBtc` with the number formatter producing "(...)" but expected "-..."
> CORE-952: ETH Unit Tests using mainnet 'loan(C)' paperKey

- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/WalletSweeper.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/TransactionApi.java
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoWalletManager.swift
- WalletKitSwift/WalletKit/common/BRBlockChainDB.swift
This avoids extraneous data from the 'GET /transactions' when 'include_raw' is 'true'.
> CORE-958: In BlockChainDB, use "include_transfers"

- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/CurrencyApi.java
- WalletKitSwift/WalletKit/common/BRBlockChainDB.swift
Given the number of ETH 'currencies', the 'GET  /currencies' might be paged.
Follows the same patterns for '/currencies' as for '/transfers', '/transactions', and '/blocks'.
> CORE-957: BlockchainDB 'GET /currencies' might be paged.

- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/NetworkDiscovery.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/CurrencyApi.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/events/network/DefaultNetworkEventVisitor.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/events/network/NetworkEventVisitor.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/events/network/NetworkUpdatedEvent.java
- WalletKitSwift/WalletKit/BRCryptoNetwork.swift
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoWalletManager.swift
- WalletKitSwift/WalletKit/common/BRBlockChainDB.swift
- WalletKitSwift/WalletKitDemo/Source/CoreDemoAppDelegate.swift
- WalletKitSwift/WalletKitDemo/Source/CoreDemoListener.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoDebugSupport.swift
Changes:
- Replace N calls to 'GET /currencies', one for each network, with one call.  
- When calling `System.configure()` multiple times, on background/foreground, announce `NetworkEvent.updated`
- Add `NetworkEvent.updated`
- Fix an error with `cryptoWalletManagerRegisterWallet()`
Also, in the Core Demo App, on foregrounding handle `NetworkEvent.updated` by registering all wallets - which will create a wallet for any currencies not previously registered.
> CORE-956: Improve System.configure()

- WalletKitSwift/WalletKitDemo/Source/TransferCreateSendController.swift
Confirmed with excessive fees:
```
APP: WVC: Want to Send
APP: TCC: Missed estimateLimitMinimum: insufficientFunds
APP: TCC: Missed estimateLimitMaximum: insufficientFunds
```
Confirmed with normal fees (able to create w/ a non-zero balance):
```
APP: WVC: TransferEvent: created
APP: WVC: TransferEvent: changed(old: Created, new: Signed)
SYS: SubmitTransaction: Error: response(404) [expected, today]
```
> CORE-966: Handle insufficientFunds from estimateLimit* in Core Demo App

- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoWalletManagerTests.swift
Will require an IOS change - argument passed to TransactionBlob.btc(...) must now be a set of values but instead a tuple of these values.  Add an extra pair of parens so that `TransactionBlob.btc(...)` becomes `TransactionBlob.btc((...)).
> CORE-962: Avoid Swift compiler warnings on {Transaction,Block,Peer}Blob.

- WalletKitCore/WalletKitCoreTests/test/bitcoin/test.c
- WalletKitCore/WalletKitCoreTests/test/bitcoin/testBwm.c
- WalletKitCore/src/bitcoin/BRWalletManager.c
- WalletKitSwift/WalletKitDemo/WalletKitDemo.xcodeproj/project.pbxproj
Also, works-around `libresolv` not being found; adds an explicit dependency to WalletKitDemo.
> CORE-964: Fix new compiler warnings from Xcode12

- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerClient.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerP.h
- WalletKitSwift/WalletKitDemo/Source/CoreDemoListener.swift
- WalletKitSwift/WalletKitDemo/Source/SummaryViewController.swift
During an 'API Sync' we get the full list of transfers/transactions and process them one-by-one; this generates a 'balance updated' event for each one.  Change the logic to generate a single 'balance updated' event after all transfers/transactions in the 'API Sync' response are processed.
Same thing when recovering the list of transfers/transactions from the FileService (persistent storage).  One 'balance updated' event after all are processed (added to the wallet).
There still are many events as each transfer is added to the wallet (allowing the UI to fill them in the 'list view').  If the App does `wallet.getBalance()` it will get the current balance, based on the added transfers/transactions.
> CORE-978: Reduce 'Balance Updated' event during API Sync and FS read.

- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/generic/BRGeneric.c
- WalletKitCore/src/generic/BRGeneric.h
- WalletKitCore/src/generic/BRGenericHandlers.h
- WalletKitCore/src/generic/BRGenericHedera.c
- WalletKitCore/src/generic/BRGenericRipple.c
- WalletKitCore/src/hedera/BRHederaTransaction.c
- WalletKitCore/src/hedera/BRHederaTransaction.h
- WalletKitCore/src/hedera/BRHederaWallet.c
- WalletKitCore/src/hedera/BRHederaWallet.h
- WalletKitCore/src/ripple/BRRippleTransfer.c
- WalletKitCore/src/ripple/BRRippleTransfer.h
- WalletKitCore/src/ripple/BRRippleWallet.c
- WalletKitCore/src/ripple/BRRippleWallet.h
Adds a GEN function genWalletUpdTransfer with XRP, HBAR implementations for BRGenericWalletUpdTransfer.  The XRP, HBAR will call `<currency>WalletUpdateTransfer` which for XRP will update the balance + sequence number and for HBAR will update the balance based on the current transfer state.  Thus submitted->{included,errored} will be handled properly.
Also updates some XRP, HBAR code for adding/removing wallet transfers to be more uniform between the currencies and to improve the computation.  Specifically adding a transfer incrementally updates the wallet balance; but removing a transfer recomputes the balance from all remaining transfers.  (Too hard to determine if the removed transfer should be subtracted off, if it was included/errored *when it was added* - so just recompute.)
> CORE-976: Add BRGenericWalletUpdTransfer

- WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
- WalletKitCore/src/ripple/BRRippleTransfer.c
- WalletKitCore/src/ripple/BRRippleTransfer.h
- WalletKitCore/src/ripple/BRRippleWallet.c
We were not updating the sequence number when adding
failed transfers from blockset
> CORE-998: Fix XRP sequence number (again)

- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoHBAR.h
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoSupportHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoSupportXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoXRP.h
- recover transfer: look up transfer by hash in wallet, skip creating if found
- fixed hash set value usage for XRP and HBAR
> CORE-1016: Check for existing transfers when recovering transfers from client bundle

- WalletKitCore/src/crypto/handlers/btc/BRCryptoBTC.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoFeeBasisBTC.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoPaymentBTC.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoTransferBTC.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletBTC.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletManagerBTC.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletSweeperBTC.c
Change `cryptoFeeBasisCreateAsBTC()` to take (fee, feePerKB, sizeInByte) but allow one to be 'UNKNOWN'.  The unknown one will be computed from the other two.
Also save the size as `sizeInKB`, as a `double` - ready for use as the "cost factor"
> CORE-1001: Save `fee` in BRCryptoFeeBasisBTC

- WalletKitCore/include/BRCryptoClient.h
- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoClientP.h
- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletManagerP2PBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerP2PETH.c
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
Submitting doesn't work for ETH, XRP yet - because the nonce/sequence-number isn't handled yet; see CORE-1009.
> CORE-985: On Transfer Submit, Keep the Containing Wallet

- WalletKitCore/WalletKitCoreTests/test/ripple/testRipple.c
- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/BRCryptoTransferP.h
- WalletKitCore/src/crypto/BRCryptoWallet.c
- WalletKitCore/src/crypto/BRCryptoWalletP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoXRP.h
- WalletKitCore/src/ripple/BRRippleTransfer.c
- WalletKitCore/src/ripple/BRRippleTransfer.h
Adds a 'Wallet Handler' that gets called on BRCryptoWallet{Add,Rem}Transfers; the handler allows subtypes to perform some actions when the wallet's transfers change.
For XRP, when a transfer is added/removed, the sequence number values are updated in BRCryptoWalletXRP.  Confirmed by sending an XRP transfer.
Note: For XRP there is no Blockset meta data with a sequence number and, generally no 'GET /accountState' endpoint.  Must iterate over the transfers to compute the sequence number.
> CORE-1009: Add `BRCryptoWalletAnnounceTransfer`

- WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletManagerXTZ.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletXTZ.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoXTZ.h
- WalletKitCore/src/tezos/BRTezosFeeBasis.c
- WalletKitCore/src/tezos/BRTezosFeeBasis.h
- removed logic to pull timer from transfer metadata
- added counter to BRTezosFeeBasis, populated from Blockset `estimate_fee` response
- fee estimation transfer is created with a 0 counter (Blockset replaces this with correct value for fee estimation RPC request)
- unrelated cleanup: refactored transaction-by-hash lookup for Tezos to handle unknown transfers (CORE-1023)
> CORE-1025: In Tezos, use counter value from estimate_fee response

- WalletKitCore/include/event/BRCryptoNetwork.h
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetworkEvent.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetworkEventType.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoSystemEvent.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletEvent.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManagerEvent.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitSwift/WalletKit/BRCryptoNetwork.swift
Also added in `CRYPTO_NETWORK_EVENT_CURRENCIES_UPDATED`.
Note that the Java Demo App is not handling the System nor Network events yet; so nothing shows in the App.  And the Unit tests don't compile; so building the library fails because it requires running some unit tests.
> CORE-1041: Update Java Event Structure Definitions

- WalletKitCore/include/BRCryptoWallet.h
- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/BRCryptoTransferP.h
- WalletKitCore/src/crypto/BRCryptoWallet.c
- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerP.h
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoSupportXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletManagerXTZ.c
- WalletKitSwift/WalletKit/BRCryptoWallet.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoWalletTests.swift
- added an internal interface for `defaultFeeBasis` in `BRCryptoWallet` for use by unit tests (replacement for deprecated `createTransferFeeBasis`)
> CORE-1000: Set transfer attributes recovered from bundle

- WalletKitCore/src/crypto/handlers/eth/BRCryptoTransferETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoTransferXTZ.c
Needs to be zero - to be consistent with "our User's perspective".  Simplifies logic that would be required to ignore the fee.  Maintains consistency with BTC/BCH/BSV.
> CORE-1050: For a RECEIVED transfer, the fee is zero for ETH, XRP, etc.

- WalletKitCore/src/bitcoin/BRWalletManager.c
- WalletKitCore/src/crypto/BRCryptoWallet.c
- WalletKitSwift/WalletKit/BRCryptoWalletManager.swift
- add network type field to `BRCryptoWalletSweeper`
- return CashAddr format address for BCH for key sweep
> CORE-981: Support BCH private key sweep

- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoClientP.h
added `qry->lock` too.  Removed REFACTOR code; BTC, etc are now synced uniformly.
> CORE-1036: Address `REFACTOR` in BRCryptoClient

- WalletKitCore/src/generic/BRGenericTezos.c
Values returned by server need to be clamped to apply minimums, this is handled by `tezosFeeBasisCreateEstimate`.
> CORE-1036: Apply minimums to Tezos fee estimation values

- WalletKitCore/src/generic/BRGenericTezos.c
Reveal operations were restricted to transactions, but the first outgoing operation may be a delegation.
> CORE-1070: In Tezos, allow reveal + delegation batch operations

- WalletKitCore/WalletKitCoreTests/test/bitcoin/test.c
- WalletKitCore/include/BRCryptoWallet.h
- WalletKitCore/src/crypto/BRCryptoWallet.c
- WalletKitCore/src/support/BRKey.c
- WalletKitCore/src/support/BRKey.h
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoExportablePaperWallet.java
- WalletKitJava/CoreNative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoExportablePaperWalletStatus.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/ExportablePaperWallet.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/WalletManager.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/ExportablePaperWallet.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/WalletManager.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/errors/ExportablePaperWalletError.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/errors/ExportablePaperWalletUnexpectedError.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/errors/ExportablePaperWalletUnsupportedCurrencyError.java
- WalletKitSwift/WalletKit/BRCryptoWalletManager.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoWalletTests.swift
Add `BRCryptoExportablePaperWallet` for generating a random single-key BTC "paper" wallet and exposing its private key and address.
> CORE-1074: Add BRCryptoExportablePaperWallet and Swift/Java interfaces

- WalletKitSwift/WalletKit/common/BRCryptoBlockset.swift
> CORE-1088: Use `BlocksetSystemClient.DEFAULT_MAX_PAGE_SIZE`

- WalletKitCore/src/tezos/BRTezosTransfer.c
Make the Tezos code mirror the Ripple code, in this case.
> CORE-1089: Respect `tezosTransferHasError()` in `tezosTransferGetAmountDirected()`

- WalletKitCore/src/crypto/handlers/eth/BRCryptoTransferETH.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerP2PETH.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerPersistETH.c
- WalletKitCore/src/ethereum/bcs/BREthereumBCS.c
- WalletKitCore/src/ethereum/blockchain/BREthereumTransactionStatus.c
- WalletKitCore/src/ethereum/blockchain/BREthereumTransactionStatus.h
- WalletKitCore/src/ethereum/les/BREthereumProvision.c
Added success state to `BREthereumTransactionStatus`, modifies persistent storage encoding.
> CORE-968: In Ethereum, handle Blockset transaction error state for included txns

- WalletKitCore/src/crypto/BRCryptoHash.c
- WalletKitCore/src/crypto/BRCryptoHashP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoNetworkBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoNetworkETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoNetworkHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoNetworkXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoNetworkXTZ.c
> CORE-1094: Encode BRCryptoHash in the native Blockchain format (no '0x' prefix for BTC)

- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/BlockchainApi.java
- WalletKitSwift/WalletKit/common/BRCryptoBlockset.swift
Blockset will add a `verified` flag to `GET /blockchains` which will impact the list of NetworkFees returned.  Add this flag to WalletKit and default it to `true`.
> CORE-1093: In `GET /blockchains` add `verified=true` for `NetworkFee`

- WalletKitCore/include/BRCryptoClient.h
- WalletKitCore/include/BRCryptoTransfer.h
- WalletKitCore/include/event/BRCryptoTransfer.h
- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoClientP.h
- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/BRCryptoTransferP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoTransferBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoTransferETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoHBAR.h
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoSupportHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoTransferXTZ.c
- WalletKitCore/src/hedera/BRHederaTransaction.c
- WalletKitCore/src/hedera/BRHederaTransaction.h
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoClient.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/TransactionApi.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/TransactionIdentifier.java
- WalletKitSwift/WalletKit/BRCryptoClient.swift
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoTransfer.swift
- WalletKitSwift/WalletKit/common/BRCryptoBlockset.swift
Note: the `POST /transactions` JSON for "transaction_id" is now uniformly passed as "unknown" rather than as "hashAsHex"; thus `hashAsHex` disappears from many interfaces.
Introduces SystemClient.TransactionIdentifier as ("transaction_id", "blockchain_id", "identifier", "hash")
> CORE-1081: Handle `POST /transactions` HTTP JSON Response

- WalletKitCore/src/crypto/BRCryptoAmount.c
- WalletKitCore/src/crypto/BRCryptoAmountP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletBTC.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletSweeperBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoFeeBasisETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletXTZ.c
- WalletKitSwift/WalletKitDemo/Source/TransferCreateSendController.swift
This fixes a `cryptoUnitGive()` crash. But not the one observed in a 'Java Stress Test'
In feeEstimation code, a 'take' was missed.  Essentially calls like:
`cryptoAmountCreateInternal(sweeper->unit, CRYPTO_FALSE, value, 0)` needed the last argument to be `1`.  Since all uses of `cryptoAmountCreateInternal()` would then use `1`, I replaced those calls with `cryptoAmountCreate()`.
Also found some missed gives in code for `cryptoWalletCreateAs<CURRENCY>`
> CORE-1083: During fee estimation, ensure the `unit` reference count.

- WalletKitCore/WalletKitCoreTests/test/crypto/testCrypto.c
- WalletKitCore/WalletKitCoreTests/test/hedera/testHedera.c
- WalletKitCore/WalletKitCoreTests/test/tezos/testTezos.c
- WalletKitCore/include/BRCryptoClient.h
- WalletKitCore/include/BRCryptoTransfer.h
- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoClientP.h
- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/BRCryptoTransferP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoTransferBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoTransferETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoTransferXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoTransferXTZ.c
- WalletKitCore/src/hedera/BRHederaTransaction.c
- WalletKitCore/src/hedera/BRHederaTransaction.h
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/Transfer.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoClientTransferBundle.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoTransfer.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/Transfer.java
- WalletKitJava/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/CoreCryptoApplication.java
- WalletKitJava/cryptodemo-android/src/main/java/com/breadwallet/cryptodemo/TransferDetailsActivity.java
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoTransfer.swift
- WalletKitSwift/WalletKitDemo/Source/TransferViewController.swift
Pending Java changes.
Only HBAR has an 'identifier' that differs from the 'hash'.  For BTC segwit, we use `txHash` (see BRTransaction.{hc}), not `wtxHash`, as the 'identifier'
> CORE-1084: Define `Transfer.identifier`

- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoWallet.swift
Make the constructor for WalletKitEvent nullable.
Java handles this already; identifier with 404 on 'ethereum-ropsten' fee estimates.
> CORE-1113: In WalletKit Swift, handle a failed 'fee basis estimate'

- WalletKitCore/src/generic/BRGeneric.c
If two transfers have UIDS, compare based on those.  Do not defer to`genericHashEqual()`.  This returns to prior logic that got messed up when adding `handlers->equal` (to do HBAR multi-serialization comparison).
> CORE-1116: Revert the `genTransferEqual()` comparison of UIDS.

- WalletKitCore/WalletKitCoreTests/WalletKitCoreTests.swift
- WalletKitCore/WalletKitCoreTests/test/crypto/testCrypto.c
- WalletKitCore/include/BRCryptoNetwork.h
- WalletKitCore/src/crypto/BRCryptoBaseP.h
- WalletKitCore/src/crypto/BRCryptoConfig.h
- WalletKitCore/src/crypto/BRCryptoNetwork.c
- WalletKitCore/src/crypto/BRCryptoNetworkP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoNetworkBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoNetworkETH.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoNetworkHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoNetworkXRP.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoNetworkXTZ.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletXTZ.c
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/Utilities.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoAddressScheme.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoNetwork.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/AddressScheme.java
- WalletKitSwift/WalletKit/BRCryptoAddress.swift
- WalletKitSwift/WalletKit/BRCryptoWalletManager.swift
- WalletKitSwift/WalletKitDemo/Source/WalletManagerViewController.swift
- WalletKitSwift/WalletKitTests/Tests/BRCryptoAccountTests.swift
This eliminates a race condition.  Lots of other small-ish changes.
- `CRYPTO_ADDRESS_SCHEME_NATIVE` - `Replaces CRYPTO_ADDRESS_SCHEME_{ETH,GEN,...}_DEFAULT`
- Initialize `BRCryptoNetwork` with default sync mode, default address scheme and currency - all constants.
- Slightly simplify implementation of `cryptoNetworkCreate{BTC,...,ETH,XRP,...}`
- In Java, handle the 'meta argument' count consistently; avoids a crash.
- Remove `cryptoNetworkSetCurrency()`
> CORE-1112: In WalletManager.init() don't initialize `addressScheme`.

- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/TransactionIdentifier.java
- WalletKitSwift/WalletKit/common/BRBlockChainDB.swift
> CORE-1120: Make 'hash' optional in TransferIdentifier

- WalletKitCore/include/BRCryptoClient.h
- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoClient.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/BlockchainDb.java
- WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/apis/bdb/TransactionApi.java
- WalletKitSwift/WalletKit/BRCryptoClient.swift
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoTransfer.swift
- WalletKitSwift/WalletKit/common/BRCryptoBlockset.swift
Add 'identifier' in the C callback to Swift/Java for 'SubmitTransfer' and provide as `cryptoTransferGetIdentifier()`.  In Blockset call, provide the "transaction_id" (name is TBD) as `blockchain_id + ":" + identifier`.
> CORE-1119: On SubmitTransfer provide a quasi-realistic 'identifier'

- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletManagerP2PBTC.c
In JIRA CORE-1059 it is noted the `Wallet Manger <currency>` tests fail because the event sequence produced is different from what the test expects.  Those tests are not fixed.  In reviewing the events, I'm not sure if the expected events are actually correct.  Going to leave the event sequences until consideration of 'callbacks vs events'.
This change does bring the API vs P2P events into (near) agreement.
> CORE-1059: Generate SYNC events in API mode

- WalletKitCore/include/BRCryptoClient.h
- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoClientP.h
- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/BRCryptoTransferP.h
- WalletKitCore/src/crypto/BRCryptoWallet.c
- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/crypto/BRCryptoWalletManagerP.h
- WalletKitCore/src/crypto/BRCryptoWalletP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoBTC.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoWalletManagerBTC.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoTransferHBAR.c
- WalletKitCore/src/crypto/handlers/hbar/BRCryptoWalletManagerHBAR.c
- WalletKitCore/src/crypto/handlers/xrp/BRCryptoWalletManagerXRP.c
- WalletKitCore/src/crypto/handlers/xtz/BRCryptoWalletManagerXTZ.c
- WalletKitJava/corecrypto/src/main/java/com/breadwallet/corecrypto/System.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryDirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/CryptoLibraryIndirect.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoSystem.java
- WalletKitJava/corenative/src/main/java/com/breadwallet/corenative/crypto/BRCryptoWalletManager.java
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKitDemo/Source/CoreDemoAppDelegate.swift
- WalletKitSwift/WalletKitDemo/Source/CoreDemoListener.swift
Changes `cwmAnnounce{BlockNumber,Transactions,...}` BRCryptoClient functions to signal events, thereby 
1. not blocking the HTTP response thread
2. ensuring that updating the BRCryptoClient and BRCryptoWalletManger state occurs in the wallet manager's thread (thus with the wallet manager's lock taken)
All BRCryptoWalletMangers will get their (default) event types from `CRYPTO_CLIENT_EVENT_TYPES`
Also: renames `cwmAnnounce...` to `cryptoClientAnnounce...` and fixes some memory issues.
> CORE-1129: Make BRCryptoClient 'Announce' as EventTypes

- WalletKitSwift/WalletKit/BRCryptoSystem.swift
Will close https://github.com/blockset-corp/walletkit/pull/14 with this merge, containing dead-code as a reminder, as a replacement.
> CORE-882:  Add `System.accountIsInitialized()` as a dead-code reminder.

- WalletKitJava/build.gradle
This version must match brd-android exactly to be included as a [composite build](https://docs.gradle.org/current/userguide/composite_builds.html).
> Update android-gradle-plugin to 4.1.3

- WalletKitCore/src/crypto/BRCryptoTransfer.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoWalletManagerETH.c
- WalletKitSwift/WalletKit/BRCryptoSystem.swift
- WalletKitSwift/WalletKit/BRCryptoTransfer.swift
Recreated this (on the proper branch, with the proper commit JIRA reference).
The Swift `cryptoTransferStateGive()` match the 'take' calls when the event is created:
```
cryptoTransferGenerateEvent (transfer, (BRCryptoTransferEvent) {
CRYPTO_TRANSFER_EVENT_CHANGED,
{ .state = {
cryptoTransferStateTake (state),
cryptoTransferStateTake (state) }}
});
```
> CORE-1141: Fix BRCryptoTransferState memory leak.

- WalletKitCore/src/crypto/BRCryptoWalletManager.c
- WalletKitCore/src/support/BRFileService.c
I've confirmed this fix numerous times.  With 'purge' the Core Demo App Android consistently crashes with a `null` pointer; without 'purge', 100% App success.
Effectively did a `git bisect` (among beta.x tags) to discover 'purge' as the issue.
> CORE-1158: Avoid `fileServicePurge()` - it causes an Android crash

- WalletKitCore/src/crypto/handlers/eth/BRCryptoAddressETH.c
- WalletKitCore/src/crypto/handlers/eth/BRCryptoETH.h
- WalletKitCore/src/crypto/handlers/eth/BRCryptoNetworkETH.c
- WalletKitSwift/WalletKitTests/Tests/BRCryptoAccountTests.swift
An invalid Ethereum address was producing `0x0000....000` instead of `null`.  Other currencies (BTC, XRP, etc) return `null` if the address string is invalid.
> CORE-1165: `cryptoNetworkCreateAddress()` returns NULL on an invalid address

- WalletKitCore/src/crypto/BRCryptoClient.c
> CORE-1172: Avoid `array_apply` in `cryptoClientAnnounceEstimateTransactionFee`

- WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/systemclient/BlocksetSystemClient.java
- WalletKitSwift/WalletKit/common/WKBlockset.swift
Added to getTransaction(), getTransfer(), getBlocks(), getBlock(). Confirmed SystemAIT tests OK (excepting subscription)
> CORE-1210: Add merge_currencies flag to blockset API calls

- WalletKitCore/src/crypto/BRCryptoClient.c
- WalletKitCore/src/crypto/BRCryptoClientP.h
- WalletKitCore/src/crypto/BRCryptoFileService.c
- WalletKitCore/src/crypto/BRCryptoFileService.h
- WalletKitCore/src/support/BRFileService.c
Adds a 'transfer version' (that is, done the right way) which allows for upgrades.  
Fixes an error in BRFileService where an upgraded entity could be read in the SQLite query; causing a conflict.
> CORE-1217: Make core-9.0.0 and core-9.0.2 use consistent persistent storage

- WalletKitCore/src/crypto/BRCryptoWalletManager.c
This code branch was meant as 'belt-and-suspenders'; never expected to be executed.  However, if it is executed then this duplicate 'release' causes a crash.
> CORE-1219: Avoid a duplicate call to `cryptoClientTransferBundleSetRelease()`

- WalletKitCore/src/ethereum/blockchain/BREthereumTransaction.c
- WalletKitCore/src/ethereum/blockchain/BREthereumTransaction.h
- WalletKitCore/src/walletkit/WKClient.c
- WalletKitCore/src/walletkit/WKClientP.h
- WalletKitCore/src/walletkit/WKWallet.c
- WalletKitCore/src/walletkit/WKWalletManager.c
- WalletKitCore/src/walletkit/WKWalletManagerP.h
- WalletKitCore/src/walletkit/handlers/btc/WKWalletManagerBTC.c
- WalletKitCore/src/walletkit/handlers/eth/WKWalletETH.c
- WalletKitCore/src/walletkit/handlers/eth/WKWalletManagerETH.c
- WalletKitCore/src/walletkit/handlers/hbar/WKWalletManagerHBAR.c
- WalletKitCore/src/walletkit/handlers/xlm/WKWalletManagerXLM.c
- WalletKitCore/src/walletkit/handlers/xrp/WKWalletManagerXRP.c
- WalletKitCore/src/walletkit/handlers/xtz/WKWalletManagerXTZ.c
- WalletKitSwift/WalletKit/WKClient.swift
- WalletKitSwift/WalletKit/WKWallet.swift
Primarily this fixes an error in ETH code whereby the `WKFeeBasis` for an estimate did not include the margin; but the low level `BREthereumTransaction` did.  The result was that  when trying to send the 'maximum' the submit would fail... because `balance - fee` was too much unless the `fee` included the margin.
The fix is to not add margin at the `BREthereumTransaction` level but instead to add margin as the estimate level.
There are a number of interface changes to accomplish this.  Notably, each blockchain needs to determine its own margin - thus there needs to be `handler`-level support.  We already have `WKWalletManagerRecoverFeeBasisFromFeeEstimateHandler`.  But, that handler needs to change such that the originating `WKTransfer` is passed in.  The margin applied might depend on the …
> CORE-1226: If appropriate (ETH, XTZ), add margin to the fee estimate.

- WalletKitCore/src/crypto/BRCryptoHash.c
This change is already on 'develop'.
> CORE-1238: In `cryptoHashEqual()` the hashes might be NULL (HBAR).

- WalletKitCore/src/crypto/BRCryptoHandlers.c
- WalletKitCore/src/crypto/BRCryptoNetworkP.h
- WalletKitCore/src/crypto/handlers/btc/BRCryptoPaymentBTC.c
Prevent a crash on the coerce of builder type by allowing BCH network type which is fine for BitPay type payment. Prevent BSV to BitPay by omitting BSV payment handler.
> CORE-1239: Crash in cryptoPaymentProtocolRequestBitPayBuilderCoerceBTC

- WalletKitCore/src/tezos/BRTezosFeeBasis.c
- WalletKitCore/src/tezos/BRTezosFeeBasis.h
- WalletKitCore/src/tezos/BRTezosOperation.c
- WalletKitCore/src/walletkit/handlers/xtz/WKWalletManagerXTZ.c
- WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/Wallet.java
- WalletKitSwift/WalletKit/WKWallet.swift
Given the current Tezos Node interface, it is not possible to compute the maximum transfer amount given a balance `B` without doing a binary search (or a truncated binary search) between `{0, B}`.  This might mean ~25 HTTP requests to Blockset which turns around with ~25 HTTP requests to the Tezos Node.
The Tezos devs suggested including OCAML, the implementation language for the Tezos Node, in WalletKit/Blockset, to do the binary search. Obviously a non-starter.
So we determine a default FeeBasis, add margin of %1000 (that is 10x the fee) - this is feeWithGift.  We estimate the fee for a transfer of 1 mutez.    Compute (balance - MAX( feeFor1Mutez, feeWithGift)) as the maximum.  User's pay too much to Tezos; but we get a maximum and can improve it in the future, perhaps as Tezos improves …
> CORE-1207: Compute the XTZ 'estimateLimitMaximum' with a Gift

- WalletKitCore/WalletKitCoreTests/test/avax/testAvalanche.c
- WalletKitCore/src/avalanche/BRAvalancheAddress.c
- WalletKitCore/src/walletkit/handlers/avax/WKAVAX.h
- WalletKitCore/src/walletkit/handlers/avax/WKNetworkAVAX.c
- WalletKitCore/src/walletkit/handlers/avax/WKWalletManagerAVAX.c
- WalletKitSwift/WalletKitTests/Tests/WKAddressTests.swift
Fixes errors exposed in Swift level testing - (WKNetwork was not initialized correctly for AVAX).
> CORE-1262: Handle the AVAX "X-" Prefix in Unit Tests

- WalletKitCore/src/walletkit/WKTransfer.c
- WalletKitCore/src/walletkit/WKTransferP.h
- WalletKitCore/src/walletkit/WKWallet.c
- WalletKitCore/src/walletkit/handlers/xtz/WKWalletXTZ.c
WKWalletXTZ.c contains the meaningful change.
Have tested on multiple 'wedged' test wallets.  Have produced as many as 3 reveals: zero, receive, send+reveal, zero, receive, send+reveal.
> CORE-1298: Handle XTZ 'addresses are garbage collected' re-reveal need.
